"""added index to name and industry

Revision ID: 172a93f61486
Revises: 4f1ec866a194
Create Date: 2026-08-21 02:30:19.850900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172a93f61486'
down_revision: Union[str, Sequence[str], None] = '4f1ec866a194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pages_industry'), 'pages', ['industry'], unique=False)
    op.create_index(op.f('ix_pages_name'), 'pages', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pages_name'), table_name='pages')
    op.drop_index(op.f('ix_pages_industry'), table_name='pages')
    # ### end Alembic commands ###
