"""changes posted_at type

Revision ID: 4a668553c113
Revises: 172a93f61486
Create Date: 2026-08-21 06:20:36.144445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4a668553c113'
down_revision: Union[str, Sequence[str], None] = '172a93f61486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'posted_at',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'posted_at',
               existing_type=sa.String(length=20),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
