"""changes headcount type to dtring

Revision ID: c63c68b3047f
Revises: 4a668553c113
Create Date: 2026-08-21 14:59:02.402047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c63c68b3047f'
down_revision: Union[str, Sequence[str], None] = '4a668553c113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'headcount',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'headcount',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
